### ISSUE TITLE
"Залишок на рахунку" stucked on October value

### ISSUE THREAD

**Issue by leechwort** [n-mouse/hacklab-money#2]
Something extraordinary happened with such a great tool!
![2022-01-03_20-29](https://user-images.githubusercontent.com/4254582/147966250-0f6f1f6a-ad56-4338-813f-5667a60eedb0.png)

**Comment by n-mouse** [comment]
Fixed!

**Comment by leechwort** [comment]
I'm so happy now!^_^ Thank you very much!:)
